USE [CookHubDB];
CREATE TABLE [dbo].[Ingredient]
(
	[Id]INT IDENTITY NOT NULL,
	[Name]NVARCHAR(50)NOT NULL,
	[Protein]INT NOT NULL,
	[Fat]INT NOT NULL,
	[Carbohydrate]INT NOT NULL,
	PRIMARY KEY CLUSTERED([Id]ASC)
);