USE [CookHubDB];
CREATE TABLE [dbo].[RecipeImage]
(
	[Id]INT IDENTITY NOT NULL,
	[RecipeId]INT NOT NULL,
	[Path]NVARCHAR(MAX) NOT NULL,
	[Extension]NVARCHAR(20),
	PRIMARY KEY CLUSTERED([Id]ASC),
	FOREIGN KEY([RecipeId]) REFERENCES [dbo].[Recipe]([Id])
);